spring.application.name=personas

server.port = 8094

infra.r2dbc.host=localhost
infra.r2dbc.port=5432
infra.r2dbc.database=person
infra.r2dbc.schema=person
infra.r2dbc.username=postgres
infra.r2dbc.password=1234


#spring.r2dbc.url=r2dbc:postgresql://localhost:5432/person
#spring.r2dbc.username=postgres
#spring.r2dbc.password=1234


#Flyway
spring.flyway.enabled= true
spring.flyway.url= jdbc:postgresql://localhost:5432/person
spring.flyway.user= postgres
spring.flyway.password= 1234
spring.flyway.schemas= person
spring.flyway.baseline-on-migrate= true
spring.flyway.locations= classpath:db/migration

# =========================
# Microservicio Bootcamp
# =========================
services.bootcamp.base-url=http://localhost:8093

# Logs generales de Spring

logging.level.org.springframework=INFO

# Logs de R2DBC y SQL
logging.level.org.springframework.r2dbc.core=DEBUG
logging.level.io.r2dbc.postgresql=DEBUG
logging.level.org.springframework.data.r2dbc=DEBUG