ALTER TABLE person.matricula
    ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    ADD COLUMN launchdate DATE NOT NULL DEFAULT CURRENT_DATE,
    ADD COLUMN duration INT NOT NULL DEFAULT 30;
